version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.0.2
workflows:
  always-run:
    jobs:
      - path-filtering/filter:
        name: check-updated-files
        mapping: |
          A/.* A-job true
          B/.* B-job true
        base-revision: master
        config-path: .circleci/continue_config.yml

