version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.0.2
workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          # <regex path-to-test> <parameter-to-set> <value-of-pipeline-parameter>
          mapping: |
            packages/A/.* A-job true
            pacakges/B/.* B-job true
          base-revision: develop
          config-path: .circleci/continue_config.yml
