version: 2.1

parameters:
  A-job:
    type: boolean
    default: false
  B-job:
    type: boolean
    default: false

jobs:
  AAA:
    docker:
      - image: circleci/node:16
    steps:
      - run: echo Hello, A
  BBB:
    docker:
      - image: circleci/node:16
    steps:
      - run: echo Hello, B
  AandB:
    docker:
      - image: circleci/node:16
    steps:
      - run: echo Hello, A and B
  no-job:
    docker:
      - image: circleci/node:16
    steps:
      - run:
          name: any packages are not updated
          command: echo ''


workflows:
  AAAAAA:
    when: << pipeline.parameters.A-job >>
    jobs:
      - AAA
  BBBBB:
    when: << pipeline.parameters.B-job >>
    jobs:
      - BBB
  run-integration-tests:
    when:
      or: [<< pipeline.parameters.A-job >>, << pipeline.parameters.B-job >>]
    jobs:
      - AandB
  no-job:
    when:
      not:
        or: [<< pipeline.parameters.A-job >>, << pipeline.parameters.B-job >>]
    jobs:
      - no-job
